[package]
name = "telepad-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "telepad_server"
path = "src/lib.rs"

[[bin]]
name = "telepad-server"
path = "src/main.rs"

[dependencies]
telepad-protocol = { path = "../telepad-protocol" }
telepad-crypto = { path = "../telepad-crypto" }
telepad-platform = { path = "../telepad-platform" }
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
thiserror.workspace = true
hostname.workspace = true
socket2 = "0.6"

[dev-dependencies]
rand.workspace = true
